name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: false
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Xóa thư mục frontend và tài liệu để tránh lỗi file nhị phân và dung lượng lớn trên HF
          rm -rf frontend/
          rm -rf docs/
          
          # Tạo một lịch sử Git mới hoàn toàn để không mang theo ảnh cũ
          rm -rf .git
          git init
          git config user.email "bot@example.com"
          git config user.name "bot"
          git add .
          git commit -m "Deploy to HF Space"
          
          # Đẩy (Force push) code mới sang HF
          git push --force https://quochiepho:$HF_TOKEN@huggingface.co/spaces/quochiepho/scanweb-api HEAD:main
